spring:
  thymeleaf:
    template-resolver-order: 0
    cache: false
  datasource:
    username: ariffnorhadi
    password: trOpOlOnes0987*&
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/play_spring
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages

server:
  error:
    include-exception: true
  port: 8080
